### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by zxl777** [youtube-py/youtube.py#2]
```
youtube/Extract.py in Get_js(req, vid)
     32         except:
     33                 match=compile(r'jsUrl":"(.*?)"')
---> 34                 src=findall(match,data)[0]
     35         if src:
     36                 return "https://www.youtube.com"+src, data

IndexError: list index out of range
```

**Comment by zxl777** [comment]
youtube baned the ip, But today worked.

**Comment by MayankFawkes** [comment]
Hello @zxl777  can you please share the video id so we can fix the problem and thank you very much for reporting we are still in beta phase.

**Comment by MayankFawkes** [comment]
Added [``GoogleReCaptchaError``](https://github.com/youtube-py/youtube.py/blob/45ac3f471706752a35596d902c4bbfd8e9d49519/youtube/Error.py#L79) exception for IP blacklisted. in [``code``](https://github.com/youtube-py/youtube.py/blob/45ac3f471706752a35596d902c4bbfd8e9d49519/youtube/Extract.py#L29-L38)
